### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by rogaha** [northwesternmutual/grammes#44]
The query fails with this error msg: 

```
goroutine 20 [running]:
github.com/northwesternmutual/grammes/gremconnect.MarshalResponse(0xc000216000, 0xc0, 0x600, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003a4000, 0x2)
	/Users/rogaha/go/pkg/mod/github.com/northwesternmutual/grammes@v1.1.2/gremconnect/response.go:63 +0x426
github.com/northwesternmutual/grammes.(*Client).handleResponse(0xc00037c310, 0xc000216000, 0xc0, 0x600, 0x0, 0x0)
	/Users/rogaha/go/pkg/mod/github.com/northwesternmutual/grammes@v1.1.2/response.go:120 +0x53
github.com/northwesternmutual/grammes.(*Client).readWorker(0xc00037c310, 0xc00002cba0, 0xc00002cc00)
	/Users/rogaha/go/pkg/mod/github.com/northwesternmutual/grammes@v1.1.2/response.go:52 +0xb2
created by github.com/northwesternmutual/grammes.(*Client).launchConnection
	/Users/rogaha/go/pkg/mod/github.com/northwesternmutual/grammes@v1.1.2/connection.go:47 +0x1bc
FAIL	mshield-ai/aegis/internal/worker/tasks/payments	0.350s
```

If I split the query (`multiple .interate() steps`) into multiple `ExecuteStringQuery` calls it works as expected. Any hints on how to handle this?

**Comment by rogaha** [comment]
solved
